on:
  push:
    branches:
      - master

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: legoktm/gh-action-auto-dch@master
        with:
          fullname: Kiwix auto robot
          email: kiwix@legoktm.com
          distro: focal

      - uses: legoktm/build-dpkg@master
        id: build
        with:
          args: --no-sign

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: output

      - uses: legoktm/gh-action-dput@master
        with:
          gpg_key: ${{ secrets.GPG_KEY }}
          repository: ppa:kiwixteam/kiwix-test
          packages: output/*_source.changes
