on:
  push:
    branches:
      - master

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: legoktm/build-dpkg@master
        id: build
        with:
          args: --no-sign

      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: "*.{deb,dsc,changes,buildinfo,tar.xz}"
