on: [push, pull_request]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        distro: [focal, bionic]
    steps:
      - uses: actions/checkout@v2

      - uses: legoktm/gh-action-auto-dch@master
        with:
          fullname: Kiwix robot test
          email: kiwix@legoktm.com
          distro: ${{ matrix.distro }}

      - uses: legoktm/build-dpkg@focal
        if: matrix.distro == 'focal'
        name: Build package for focal
        id: build-focal
        with:
          args: --no-sign

      - uses: legoktm/build-dpkg@eoan
        if: matrix.distro == 'eoan'
        name: Build package for eoan
        id: build-bionic
        with:
          args: --no-sign

      - uses: legoktm/build-dpkg@bionic
        if: matrix.distro == 'bionic'
        name: Build package for bionic
        id: build-bionic
        with:
          args: --no-sign

      - uses: actions/upload-artifact@v2
        with:
          name: Packages for ${{ matrix.distro }}
          path: output

      - uses: legoktm/gh-action-dput@master
        name: Upload dev package
        # Only upload on pushes to master
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
        with:
          gpg_key: ${{ secrets.GPG_KEY }}
          repository: ppa:kiwixteam/kiwix-test
          packages: output/*_source.changes

      - uses: legoktm/gh-action-dput@master
        name: Upload release package
        # Only upload on pushes to master or tag
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        with:
          gpg_key: ${{ secrets.GPG_KEY }}
          repository: ppa:kiwixteam/kiwix-test
          packages: output/*_source.changes

